# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a273e3c7a6ed0b165329d01d3f162beed4fe7ee6317b011c7a0cdaef05f984519d5e54fca53c41e316ddc213757e63d11551d44b64d99a80c1a0d426434020

test:
  secret_key_base: 3e078dbe2e129f6d793103eb68b24662eef4cac42081fd3273e7adb6836c70e0b965fda986a1ea174ed2251759a7ca88fc2cf7e56ff249a875f167ca304e690f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
